# Generated by Django 5.1.2 on 2024-12-27 09:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='continent_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country_id',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='pmpapp.country'),
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='pmpapp.continent'),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='pmpapp.country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='employee_types', to='pmpapp.country'),
            preserve_default=False,
        ),
    ]
