# Generated by Django 5.1.2 on 2024-12-27 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0002_rename_state_id_city_state_remove_city_country_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='pmpapp.city'),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='pmpapp.state'),
        ),
    ]
