# Generated by Django 5.1.2 on 2024-12-29 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0003_employee_city_employee_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Setup', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeetype',
            options={'verbose_name': 'Employee Type', 'verbose_name_plural': 'Employee Types'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        
        migrations.AddField(
            model_name='employeetype',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_Types', to='pmpapp.country'),
        ),
    ]
