# Generated by Django 5.1.2 on 2025-01-03 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0006_team_country_cnic_number_mask_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Authentication and Authorization', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='country',
            name='cnic_number_mask',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='phone_number_mask',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Project_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to='pmpapp.employee'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='pmpapp.TeamMember', to='pmpapp.employee'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pmpapp.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='pmpapp.city'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pmpapp.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='pmpapp.state'),
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('Client_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Client_Name', models.CharField(max_length=150, unique=True)),
                ('Client_ID', models.CharField(editable=False, max_length=150)),
                ('Client_City', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pmpapp.city')),
                ('Client_Country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pmpapp.country')),
            ],
        ),
    ]
