# Generated by Django 5.1.2 on 2025-01-05 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0008_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('interval', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Project Interval',
                'verbose_name_plural': 'Project Intervals',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Project Type',
                'verbose_name_plural': 'Project Types',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='continent',
        ),
        
        migrations.AddField(
            model_name='project',
            name='project_interval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='pmpapp.projectinterval'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='pmpapp.projecttype'),
        ),
    ]
