# Generated by Django 5.1.2 on 2025-01-05 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0009_projectinterval_projecttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Client_Name',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='pmpapp.clients'),
            preserve_default=False,
        ),
    ]
