# Generated by Django 5.1.2 on 2025-01-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0011_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(editable=False, max_length=150, unique=True),
        ),
    ]
