# Generated by Django 5.1.2 on 2025-01-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0013_project_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_members',
        ),
        migrations.AddField(
            model_name='task',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='pmpapp.employee'),
        ),
    ]
