# Generated by Django 5.1.2 on 2025-01-08 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0017_rename_client_name_project_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Client_ID',
            field=models.CharField(editable=False, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Client_Name',
            field=models.CharField(max_length=150),
        ),
        
        migrations.AddField(
    model_name='project',
    name='project_name',
    field=models.CharField(max_length=100),
)
    ]
