# Generated by Django 5.1.2 on 2025-01-09 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0018_alter_clients_client_id_alter_clients_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Client_ID',
            field=models.ForeignKey(db_column='Client_ID', on_delete=django.db.models.deletion.CASCADE, to='pmpapp.clients'),
        ),
    ]
