# Generated by Django 5.1.2 on 2025-01-09 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0019_alter_project_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Client_ID',
            field=models.ForeignKey(db_column='Client_ID', on_delete=django.db.models.deletion.CASCADE, to='pmpapp.clients', to_field='Client_ID'),
        ),
    ]
