# Generated by Django 5.1.2 on 2025-01-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0021_task_parent_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Client_ID',
            field=models.ForeignKey(db_column='Client_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pmpapp.clients', to_field='Client_ID'),
        ),
    ]
