# Generated by Django 5.1.2 on 2025-01-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0023_alter_task_parent_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_interval',
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'parent_task')},
        ),
    ]
