# Generated by Django 5.1.2 on 2025-01-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0026_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.CharField(blank=True, null=True, verbose_name='self'),
        ),
    ]
