# Generated by Django 5.1.2 on 2025-01-15 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0031_customuser_employee_profile_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employee_profile',
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
