# Generated by Django 5.1.2 on 2025-01-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpapp', '0033_task_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sr_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
